# Main configuration file for ${project.name} v${project.version}

# localized language support
language: en-US

# If this list is empty, all worlds will be added to the enabled worlds list
enabled-worlds:
#  - enabled_world1
#  - enabled_world2

# These worlds will be removed from the enabled worlds list
disabled-worlds:
  - disabled_world1
  - disabled_world2

# material to be used as default item
default-material: NETHER_STAR

# allow giving and binding with items of default material only
default-material-only: false

# minimum distance from destination to use
minimum-distance: 10

# cooldown time in seconds
teleport-cooldown: 60

# warmup time in seconds
teleport-warmup: 5

# particle effects during warmup
particle-effects: true

# play sound effects
sound-effects: true

# lightning strike at destination on use
lightning: true

# Allow left-click to use
left-click: false

# require shift-click to use LodeStar item
shift-click: true

# send player to world spawn if they do not have a home bed spawn set
bedspawn-fallback: true

# remove item from inventory ( on-use | on-success | never )
remove-from-inventory: on-success

# allow LodeStar items to be used in crafting recipes
allow-in-recipes: false

# cancel teleport if player takes damage
cancel-on-damage: false

# cancel teleport if player moves
cancel-on-movement: false

# cancel teleport if player interacts with another block
cancel-on-interaction: false

# maximum number of spawn star items that can be given at once (-1 for no limit)
max-give-amount: -1

# if player is in netherworld, try to respawn in matching overworld
from-nether: true

# if player is in end world, try to respawn in matching overworld
from-end: true

# write log entry on use
log-use: true
